version: '3.1'
services:
    app:
        build: ./app
        container_name: app
        restart: always
        ports:
           - 8080:3000
        networks:
            - backend

networks:
    backend:
        driver: bridge
